### ISSUE TITLE
fix: lazyflex should skip plugins having enabled = false

### ISSUE THREAD

**Issue by abeldekat** [abeldekat/lazyflex.nvim#31]
The intention of the plugin should be to only operate on active plugins in the configuration. Plugins the user disabled should be skipped.

#### Prerequisite:
A config using LazyVim, where `mini.comment` is disabled and replaced with another plugin.
On startup, without lazyflex, `mini.comment` is shown in the UI, in section disabled. The plugin can be cleaned

#### Enable
```lua
{
    "abeldekat/lazyflex.nvim",
    import = "lazyflex.hook",
    opts = {
      lazyvim = { presets = { "coding" } },
      kw = { "toky" },
    },
}

{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
{ "echasnovski/mini.comment", enabled = false }
```
Result, correct: `mini.comment` is still shown in section disabled and can be cleaned

Lazyflex attached `cond=true` to `mini.comment`. When `cond = true`, the `enabled` property determines if the plugin is *enabled* or *disabled*.

#### Disable
```lua
{
    "abeldekat/lazyflex.nvim",
    import = "lazyflex.hook",
    opts = {
      enable_match = false,
      lazyvim = { presets = { "coding" } },
    },
}

{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
{ "echasnovski/mini.comment", enabled = false }
```

Result, wrong: `mini.comment` is shown in section disabled as **conditionally** *disabled* and can **not** be cleaned

This happens because **lazyflex** attaches `cond=false` to all plugins that match, including `mini.comment`. The plugin is moved to the internal list of disabled plugins, and the `enabled` property is not consulted anymore.

**Comment by dpetka2001** [comment]
Was just about to make an issue in Lazyvim about this (they enabled `fzf-native` for Telescope by default and I wanted to use `zf-native` instead). Glad I saw this issue, because I also remember that `enabled = false` would allow me to clean the plugins. Thought maybe something in `lazy.nvim` changed the way it handles things.
