### ISSUE TITLE
can't call old_colleague()

### ISSUE THREAD

**Issue by sunjon** [abeldekat/lazyflex.nvim#63]
Hola.
There's not more than one Abel De Kat - right? :)

**Comment by abeldekat** [comment]
Hello @sunjon,

I don't quite understand the question.

**Comment by sunjon** [comment]
It was my failed attempt to be funny! :)

When I'd stumbled across your repo, I'd assumed you were someone I knew and worked with named Abel De Kat in Stockholm.

If you're not the Abel I know (check my profile for some info) living in .nl, feel free to close the issue!

**Comment by abeldekat** [comment]
No problem!
