### ISSUE TITLE
How do I add it to lazyvim?

### ISSUE THREAD

**Issue by gerroon** [abeldekat/lazyflex.nvim#69]
Hi

The doc mentions to install with LazyVim but it does not tell where to add. Can you please clarify about where or which file to add this code ?

```
require("lazy").setup({
  spec = {
    {
      "abeldekat/lazyflex.nvim",
      version = "*",
      cond = true,
      import = "lazyflex.hook",
      opts = {},
    },
    -- your plugins:
    -- { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- { import = "plugins" },
  },
})

```

**Comment by abeldekat** [comment]
Hello @gerroon,

The installation is done by [lazy.nvim](https://github.com/folke/lazy.nvim#-installation), the package manager that powers [LazyVim](https://github.com/LazyVim/LazyVim#-features).

If you installed `LazyVim` according to the [docs](https://www.lazyvim.org/installation), the file to use is [lua.config.lazy.lua](https://github.com/LazyVim/starter/blob/92b2689e6f11004e65376e84912e61b9e6c58827/lua/config/lazy.lua#L11), located in your `nvim` folder.

**Comment by gerroon** [comment]
thanks!

> Hello @gerroon,
> 
> The installation is done by [lazy.nvim](https://github.com/folke/lazy.nvim#-installation), the package manager that powers [LazyVim](https://github.com/LazyVim/LazyVim#-features).
